user:
  nick: kanzashi
  user: kanzashi
  real: kanzashi the accessory
server:
  # bind: 0.0.0.0
  # port: 8081
  # tls: true
  pass: proxy_pass
  # Or SHA2 sum is acceptable.
  # pass: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
networks:
  network_name: # network name is used for channel name.
    host: irc.example.org
    port: 6667
    encoding: UTF-8
    # tls: true

  # -- Examples
  # ircnet:
  #   host: irc.ircnet.ne.jp
  #   port: 6668
  #   encoding: ISO-2022-JP
  # friend:
  #   host: irc.friend-chat.jp
  #   port: 6664
  #   encoding: ISO-2022-JP
  # freenode:
  #   host: irc.freenode.net
  #   port:  7070
  #   encoding: utf-8
  #   tls: true

plugins:
  detached_nick: # Change nickname when any client isn't connected (detached).
    enabled: false
    nick_on_detached: kanzashi_off # nick when detached
  detached_away: # Set AWAY when any client isn't connected (detached).
    enabled: false
    message: "sleeping" # away message will set when detached



# plugin_name:
#   enabled: false
