user:
  nick: kanzashi
  user: kanzashi
  real: kanzashi the accessory
server:
  # bind: 0.0.0.0
  # port: 8081
  # tls: true
  pass: proxy_pass
  # Or SHA2 sum is acceptable.
  # pass: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
networks:
  network_name: # network name is used for channel name.
    host: irc.example.org
    port: 6667
    encoding: UTF-8
    # tls: true

  # -- Examples
  # ircnet:
  #   host: irc.ircnet.ne.jp
  #   port: 6668
  #   encoding: ISO-2022-JP
  # friend:
  #   host: irc.friend-chat.jp
  #   port: 6664
  #   encoding: ISO-2022-JP
  # freenode:
  #   host: irc.freenode.net
  #   port:  7070
  #   encoding: utf-8
  #   tls: true

plugins:
  detached_nick: # Change nickname when any client isn't connected (detached).
    enabled: false
    nick_on_detached: kanzashi_off # nick when detached
  detached_away: # Set AWAY when any client isn't connected (detached).
    enabled: false
    message: "sleeping" # away message will set when detached
  join_when_invited: # join specified channel when invited
    enabled: false
  log:
    enabled: false
    # whether or not to keep log files open
    keep-file-open: true
    # directory to record logs
    directory: log
    # format of every lines' header. if omitted, Kanzashi uses "%H:%M".
    filename: "%Y.%m.%d.txt"
    # mode of log files. default value is 0600.
    mode: 0600
    # mode of directory. default value is 0700.
    dir-mode: 0700
    # mask for command to record logs. if omitted, Kanzashi records about all channels.
    command: privmsg,join,part,kick,invite,mode,nick,quit,kill,topic,notice
    # whether or not to change formats when your own messages in PRIVMSG/NOTICE. default value is true.
    distinguish-myself: true
    # regular expression to specify channels to record. if omitted, Kanzashi records about all channels.
    channel:
# plugin_name:
#   enabled: false
